name: CI
on:
  push: { branches: [ "main", "feature/**" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m venv .venv
      - run: . .venv/bin/activate && pip install -r requirements.txt
      - run: cp .env.example .env
      - run: . .venv/bin/activate && python - <<'PY'
import sys, importlib; importlib.import_module("config.wsgi"); print("WSGI OK")
PY
