# Generated by Django 5.2.7 on 2025-10-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('counterparty_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LEGAL', 'Юрлицо'), ('PERSON', 'Физлицо'), ('IE', 'ИП'), ('SELFEMP', 'Самозанятый'), ('BANK', 'Банк')], max_length=16)),
                ('country_profile', models.CharField(choices=[('RU', 'Russia'), ('US', 'USA'), ('UK', 'United Kingdom'), ('EU', 'European Union'), ('DE', 'Germany'), ('FR', 'France'), ('IN', 'India'), ('CN', 'China'), ('NG', 'Nigeria')], max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('MERGED', 'MERGED'), ('LIQUIDATED', 'LIQUIDATED')], default='ACTIVE', max_length=16)),
                ('display_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['counterparty_id'],
            },
        ),
    ]
